SELECT SALARY 
FROM EMPLOYEES
WHERE SALARY > 5000;

SELECT FIRST_NAME, LAST_NAME, JOB_ID
FROM employees
WHERE JOB_ID = 'IT_PROG';

SELECT * 
FROM EMPLOYEES
WHERE LAST_NAME='King';

SELECT * 
FROM EMPLOYEES 
WHERE department_id=90;

SELECT * 
FROM employees 
WHERE salary >= 15000;